image: node:22.3.0-bullseye

stages:
  - prepare
  - build
  - publish

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - node_modules

install:
  stage: prepare
  script:
    - npm install

test:
  stage: build
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1h
  only:
    - master
    - merge_requests

publish:
  stage: publish
  script:
    - "echo VALUE: \"$JOB_VARIABLE\""
    - apt update
    - apt install -y zip
    - cd dist
    - zip website.zip -r .
    - wget https://dl.min.io/client/mc/release/linux-amd64/mc -v -O /bin/mc
    - chmod +x /bin/mc
  artifacts:
    paths:
      - dist/website.zip
  when: manual
  variables:
    JOB_VARIABLE:
      value: "hello, world!"
      description: "This is an example variable for the publish job"
